### ISSUE TITLE
Description is wraped in html tags

### ISSUE THREAD

**Issue by lichtist** [jgonyea/grav-plugin-podcast#15]
The description is wraped in html tags.:
`<p pass="episode-description">"<p>This is a description</p>"</p>`

should be

`<p class="episode-description">This is a description</p>`

**Comment by lichtist** [comment]
in podcast/templates/partials/podcast_episodes_list.html.twig

**Comment by jgonyea** [comment]
Thanks.  I'll fix by end of day today along with a couple other minor tweaks.

**Comment by jgonyea** [comment]
Fixed in new release.

**Comment by jgonyea** [comment]
Fixed in new release.
