### ISSUE TITLE
RSS renders blank site

### ISSUE THREAD

**Issue by lichtist** [jgonyea/grav-plugin-podcast#16]
.../podcast.rss is blank when podcast plugin is enabled.
It renders after disabling the plugin

**Comment by jgonyea** [comment]
Can you describe your file structure?  Generally, you create a channel and place episodes underneath.  Navigating to channel page and then adding ".rss" at the end (i.e. local.dev/test-channel.rss) should provide the rss feed.

Also, can you let me know what versions of Grav core, podcast, feed, and getid3 you are running?

Thanks.

**Comment by jgonyea** [comment]
Closing ticket due to no response.  Will reopen if more information comes in.
