### ISSUE TITLE
summary can truncate html, and break it

### ISSUE THREAD

**Issue by krodelabestiole** [jgonyea/grav-plugin-podcast#18]
I tried to implement an audio player manually since I get a "no audio" message and no audio player working then I had my html broken.

I think this method is too simplistic :
{{ (episode.summary)|truncate(120) }}
line 27 https://github.com/jgonyea/grav-plugin-podcast/blob/develop/templates/partials/podcast_episodes_list.html.twig

I guess the fact that audio player doesn't work might have something to do with the lack of metadata. still it should be able to work anyway.

**Comment by jgonyea** [comment]
Fixed in new release.
