### ISSUE TITLE
Extra slash in front of remote URL

### ISSUE THREAD

**Issue by tlflow** [jgonyea/grav-plugin-podcast#20]
I'm copying and pasting the URL into the "External Files" field on the Podcast Audio tab of a Podcast Episode page. Now, after saving the page, there's an extra "/" in front of the path so the path won't work as it's trying to make the path a relative path. 

For example, <audio controls="1" alt="episode.title"><source src="/https://s3.amazonaws.com/...

(see the slash in front of the https:// above?)

I don't think this was doing this before the last update but it's breaking my podcast links now.

**Comment by jgonyea** [comment]
Crud, you're right.  I forgot about the absolute urls. I'll push a fix shortly.

**Comment by jgonyea** [comment]
@tlflow If possible, could you send me a copy of your header matter to check against?  Thanks!

**Comment by tlflow** [comment]
Sure, here goes the matter from my client's podcast:

title: 'I Have What It Takes'
subtitle: 'Real Talk Table Talk Sermon Series'
podcast:
    audio:
        remote: 'https://s3.amazonaws.com/copclt-media/sunday-services/2018/I+Have+What+it+Takes+5-20-18.mp3'
        meta:
            guid: 'https://s3.amazonaws.com/copclt-media/sunday-services/2018/I+Have+What+it+Takes+5-20-18.mp3'
            type: audio/mpeg
            duration: '1:16:33'
            enclosure_length: 64380226
    itunes:
        author: 'Church of Philadelphia Media Team'
        explicit: 'no'
date: '19:55 23-05-2018'
creator: tflowers

**Comment by jgonyea** [comment]
Pushing fix now.  Check your gpm shortly.

Thank you @tlflow for your patience.
