### ISSUE TITLE
Layout/Styling

### ISSUE THREAD

**Issue by ElliotWilde** [jgonyea/grav-plugin-podcast#21]
Hey, 

This may have been opened and answered elsewhere or I might be missing something. 

Are the podcast pages supposed to inherit the styling of the theme? 

I tried a few themes but always get the same 'broken' looking layout and theming on the podcast pages. 

Pic: https://ibb.co/eco63o

Cheers
Elliot

**Comment by jgonyea** [comment]
Styling needs attention in this plugin, that's for sure. I'll see what I can do to follow more of a theme's styling.

**Comment by jgonyea** [comment]
Episodes seem to look OK, but the podcast pages are definitely broken.

**Comment by reiner** [comment]
Hey there. I was wondering if miss any Grav settings here? HTML parameters are showing up 
https://reinergaertner.de/podcast

Do you have any quick fix for that?

Thank you

**Comment by sdelice** [comment]
Hi, 
In definitive, does the podcast page inherit the stylling of the page ? Is it possible to customize the player ?

**Comment by jgonyea** [comment]
All pages will be getting a major overhaul in v3.0.0.  I hope to get it out this weekend.

**Comment by jgonyea** [comment]
Fixed in v3.0.0
