### ISSUE TITLE
Check file exists

### ISSUE THREAD

**Issue by dragonito** [jgonyea/grav-plugin-podcast#23]
Check if file exists in /user/plugins/podcast/podcast.php:166

```php
public static function retreiveAudioType($file)
```

if you remove file and add it new, the old files are in configuration. Perhaps you could add a filecheck, it not there will be a big exception.

**Comment by jgonyea** [comment]
Can you tell me more of what you mean by the old files are in configuration?

Thanks

**Comment by jgonyea** [comment]
This will get solved with #12
