### ISSUE TITLE
Podcast Plugin Kills all RSS Feeds on Site

### ISSUE THREAD

**Issue by Pixaster** [jgonyea/grav-plugin-podcast#25]
Hi there! Having kinda the same problem like lichtist on 9 May 2018. When activating the podcast plugin, every RSS on my website will be blank and I cant figure out why. For example, the blog.rss works perfectly fine as long the plugin isn't installed or activated. The generated .rss for Podcast-Channel is also blank. Running on Podcast v2.1.4, GetId3 v1.0.3, Feed  v1.7.1 and Grav 1.6.9.

Thanks a bunch!

**Comment by jgonyea** [comment]
Thanks for the report. I'll look into this as soon as I can.

**Comment by jgonyea** [comment]
Would you be willing to share your site (or at least a stub of it) so I can figure the problem out?

**Comment by Pixaster** [comment]
Of course: http://reaperette.com/Testgrav/grav-admin/ 

Was playing around a bit more and figured out, that the podcast plugin didn't liked that I put "de" in the supported languages and also forced "de" as language in grav config. So the Podcast RSS feed works now - but the main blog.rss is still dead.

thanks for the support!

**Comment by jgonyea** [comment]
I don't have much experience with other languages. Could you send me a zip of your site that I could troubleshoot?

**Comment by Pixaster** [comment]
hi! Short heads up - I'm busy over the next few days. I should be able to provide you a zip on monday. Have a nice weekend!

**Comment by Pixaster** [comment]
So - here is the directory. If you need it  User: pixaster PW: Admin1234
http://www.reaperette.com/podtest.rar

there is nothing of value on there

**Comment by jgonyea** [comment]
Addressed in ver 2.1.5
