### ISSUE TITLE
Undefined index: mime_type with remote podcast

### ISSUE THREAD

**Issue by marywarrington** [jgonyea/grav-plugin-podcast#26]
I'm getting the attached error when I try to save a remotely hosted podcast. It doesn't happen locally, but does on our live site, which leads me to think it's a permissions issue. Any guidance would be greatly appreciated!

<img width="1034" alt="Screen Shot 2019-12-10 at 8 45 59 AM" src="https://user-images.githubusercontent.com/16548012/70550002-f7030200-1b29-11ea-85a8-f22256534762.png">

**Comment by jgonyea** [comment]
Can you send me the URL of your remote resource?

**Comment by marywarrington** [comment]
@jgonyea turns out this was a server permissions / corrupt file issue! Closing the issue!
