### ISSUE TITLE
No processing in multilang websites

### ISSUE THREAD

**Issue by leonceaklin** [jgonyea/grav-plugin-podcast#28]
The plugin doesn't get the metadata of audio files when the Grav installation has multiple languages enabled.

This is because of [line 83 in podcast.php](https://github.com/jgonyea/grav-plugin-podcast/blob/develop/podcast.php#L83):
`if (!($obj instanceof \Grav\Common\Page\Page) || $obj->name() != 'podcast-episode.md') {`

In my setup, `$obj->name()` has the value `podcast-episode.de.md`.
You should replace the line with:
`if (!($obj instanceof \Grav\Common\Page\Page) || $obj->template() != 'podcast-episode') {`
`$obj->template()` has always the same value regardless of the language.

In the template files you should change every occurrence of the `page.name` property to `page.template`

Thank you!

**Comment by jgonyea** [comment]
Addressed in ver 2.1.5
