### ISSUE TITLE
Missing brackets

### ISSUE THREAD

**Issue by PalmTreeVI** [jgonyea/grav-plugin-podcast#31]
File  /user/plugins/podcast/templates/partials/podcast_episodes_list.html.twig
Missing {{ }} around alt="episode title" currently line 39
`                        <audio controls="1" alt="episode.title"><source src="{{media_url}}">Your browser does not support the audio tag.</audio>
`

**Comment by jgonyea** [comment]
Fixed in 2.1.7  Thanks!
