### ISSUE TITLE
Save Failed: Cannot set nested property header podcast audio local {$filename}.mp3 on non-array value

### ISSUE THREAD

**Issue by sdelice** [jgonyea/grav-plugin-podcast#32]
Hi,
Since i've update the plugin on my Grave CMS instance, i'm no more enable to create and save new page. For exemple i have this error below :
Save Failed: Cannot set nested property header podcast audio local {$filename}.mp3 on non-array value

Is it a bug ?

**Comment by jgonyea** [comment]
Hi,

Which version of Grav, admin, and podcast plugins are you running?

**Comment by sdelice** [comment]
Thanks in advance for taking my issue into consideration. 
Here wich version of grav admin and podcast plugin i'm running : 
 Admin Panel  v1.10.0-rc.17 test release
 Admin Addon Media Metadata v1.1.0
Podcast v2.1.7

**Comment by sdelice** [comment]
Any idea ?

**Comment by jgonyea** [comment]
Can you try again with the stable version of the admin plugin?

**Comment by sdelice** [comment]
Every thing is OK with the stable version of the admin plugin. 
Thanks you !
