### ISSUE TITLE
Ensure Grav 1.7 Compatibility

### ISSUE THREAD

**Issue by jgonyea** [jgonyea/grav-plugin-podcast#36]
Make sure that podcast is compatible with Grav v1.7.

Known issues:

~~* #38 Save Failed: Cannot set nested property~~
~~* #35 RSS not being generated~~
~~* #21 Layout and styling needs work~~
~~* #10 Series and Episode pages should link upwards to their respective parents~~
~~* https://github.com/getgrav/grav-plugin-auto-date/issues/8 Auto-date not working on Grav 1.7~~

Notes:
Auto-date requirement removed.  Functionality moved into podcast.php.

**Comment by jgonyea** [comment]
There's an issue with the content on an episode page.  Will push a fix shortly

**Comment by jgonyea** [comment]
Everything appears to be working in 2.1.9

**Comment by rzw** [comment]
This is still an issue. I get:

Save Failed: Cannot set nested property header podcast audio local {$filename}.mp3 on non-array value

Grav v1.7.3 - Admin v1.10.2
PHP Version 7.4.11

Is there a workaround? Can I just upload a file and enter path in episode?

**Comment by jgonyea** [comment]
@rzw, see #38 for current workaround

**Comment by jgonyea** [comment]
@rzw, a new 3.0.0 release should be coming out this weekend to address all items above in this meta ticket.

**Comment by rzw** [comment]
I haven't tested. But thanks.
