### ISSUE TITLE
Using "feed" instead of "content" in frontmatter breaks feed plugin

### ISSUE THREAD

**Issue by graphographer** [jgonyea/grav-plugin-podcast#41]
Feed v1.8.5 will only generate RSS for pages that contain a `content` field in its frontmatter. Meanwhile, Podcast v3.0.1 creates a podcast channel with a `feed` field instead. When `www.example.com/my-channel.rss` is visited, the regular HTML page is rendered instead of XML. Changing `feed` to `content` causes everything to work as expected.

**Comment by jgonyea** [comment]
Sorry, I haven't been able to reproduce what you're seeing.  Could you send me an example set of pages?

**Comment by jgonyea** [comment]
This is now fixed in Podcast v3.0.3.  Resave existing content will automatically fix the header to include the appropriate fields.  New content will contain the fields automatically.
