### ISSUE TITLE
HTML page generated instead of RSS feed

### ISSUE THREAD

**Issue by ianharrier** [jgonyea/grav-plugin-podcast#42]
Something similar to #35 might be happening again. Both my [.rss URL](https://www.stlyabsf.org/podcast.rss) and @hiperterminal's [.rss URL](http://hiperterminal.com/septetocamajan/es/.rss) seem to be generating the HTML page rather than the RSS feed.

In my case, I'm running:
- Grav 1.7.21
- Admin 1.10.21
- Feed 1.8.5
- GetId3 1.0.3
- Podcast 3.0.1

I've tried reading through the source code for the podcast plugin, but I'm not great with modern PHP, so I'm not exactly sure what to look for to troubleshoot. Please let me know what I can do to help!

Thank you!

**Comment by jgonyea** [comment]
Thanks for the info!

I'll look at this shortly

**Comment by jgonyea** [comment]
I think the issue stems from the Feed plugin.  For now, rollback the feed plugin to version 1.8.1 as the current workaround, @ianharrier

**Comment by ianharrier** [comment]
Thank you! I can confirm that rolling the Feed plugin back to 1.8.1 resolves the issue.

**Comment by jgonyea** [comment]
Glad it's working for you again.  I'll try to find out if there's something I'm doing wrong with the podcast plugin with regards to the feed plugin.

**Comment by jgonyea** [comment]
This is now fixed in Podcast v3.0.3.  Resave existing content will automatically fix the header to include the appropriate fields.  New content will contain the fields automatically.

**Comment by ianharrier** [comment]
3.0.3 fixed the issue for me. Thank you, @jgonyea!
