### ISSUE TITLE
Can't Mark Episode not explicit

### ISSUE THREAD

**Issue by PlayBoxTech** [jgonyea/grav-plugin-podcast#43]
Adding my first episode and it giving me the warning: 
# Invalid input in "Explicit Content"
## Failed to save entry: Form validation failed, please check your input

However if you check the image its marked as not explicit. Is there something I'm missing?
![ArcoLinux_2021-10-01_16-04-38](https://user-images.githubusercontent.com/35372112/135686280-af891b4f-721b-42aa-b152-d56c99428f19.png)

**Comment by PlayBoxTech** [comment]
Per your request: 

- Admin Panel v1.10.23
- Breadcrumbs v1.6.1
-  Feed v1.8.5
-  GetId3 v1.0.3
-  Podcast v3.0.1
- Grav 1.7.13

**Comment by jgonyea** [comment]
I believe this is now fixed in Podcast v3.0.2
