### ISSUE TITLE
Suggestion: Default Episode Author

### ISSUE THREAD

**Issue by PlayBoxTech** [jgonyea/grav-plugin-podcast#44]
It would be cool if the Episode Author could be pre-filled in based on Plugin settings.

**Comment by jgonyea** [comment]
I like this idea.

Would taking the currently signed in grav user's name (not username) as the default suffice?

**Comment by PlayBoxTech** [comment]
Yes, that would work also

**Comment by jgonyea** [comment]
Fixed in 3.0.4
