### ISSUE TITLE
"Array and string offset access syntax with curly braces is no longer supported"

### ISSUE THREAD

**Issue by snowboarder04** [jgonyea/grav-plugin-podcast#46]
I'm trying to add a regular, short .mp3 as an episode but I'm getting this error when hitting 'Save' on an episode page. 

I've tried updating the idv3 tags using a couple of different apps but it doesn't seem to make any difference.

```
3
Whoops\Exception\ErrorException
…/user/plugins/get-id3/library/getid3.php401
2
Whoops\Run handleError
…/vendor/filp/whoops/src/Whoops/Run.php486
1
Whoops\Run handleShutdown
…/system/src/Grav/Common/Errors/SystemFacade.php43
0
Grav\Common\Errors\SystemFacade handleShutdown
[internal]0
```

**Comment by snowboarder04** [comment]
Ah, yeah, apparently I'm running PHP 8.0.12 :/

**Comment by jgonyea** [comment]
This is an issue with the get-id3 php library being used.
See https://github.com/jgonyea/grav-plugin-get-id3/issues/6
