### ISSUE TITLE
Is there a way to setup basic http auth ?

### ISSUE THREAD

**Issue by Limezy** [jgonyea/grav-plugin-podcast#47]
Hi !
Thanks for this awesome project.
I would like to setup a private podcast --> is there a way to setup basic http auth ?
I've tried using a restriced login access to the podcast page, but that seems not to be compatible with Apple Podcast app.
Thanks :)

**Comment by jgonyea** [comment]
Basic http auth would be something you would setup via your apache application
https://httpd.apache.org/docs/2.4/howto/auth.html
