### ISSUE TITLE
Is there a max upload size setting somewhere ?

### ISSUE THREAD

**Issue by Limezy** [jgonyea/grav-plugin-podcast#48]
If yes, I didn't find it. I get that annoying warning every time I try to upload an episode .mp3:
![image](https://user-images.githubusercontent.com/24638389/142606240-9bb12b10-1fe2-475b-a11a-042d6c6a76a3.png)
Thanks for your kind help

**Comment by jgonyea** [comment]
First place to check is your php.ini file. Look for the parameter max_upload_size

https://stackoverflow.com/questions/2184513/change-the-maximum-upload-file-size#2184541

If that is already changed to be larger that your ~42MB file, then check the podcast plugin settings.

**Comment by Limezy** [comment]
Many thanks for your fast answer. I'll check as per your advice.

**Comment by Limezy** [comment]
It worked after both changing nginx setting and adding the following in my `/etc/php/7.3/fpm/pool.d/grav.conf`

```
php_admin_value[upload_max_filesize] =100M
php_admin_value[post_max_size] =100M
```

Thanks again for your help !
