### ISSUE TITLE
In English, the word "series" must not be pluralize

### ISSUE THREAD

**Issue by aleclerc7** [jgonyea/grav-plugin-podcast#49]
Hello,

**podcast_series_list.html.twig line 3**:
`{{ 'PLUGIN_PODCAST.WORDS.SERIES'|t|e|pluralize }}`
should be:
`{{ 'PLUGIN_PODCAST.WORDS.SERIES'|t|e }}`

Otherwise it gives the word "Sery" which is not an English word. Series is series in singular and plural. :-)

Kind regards.

**Comment by jgonyea** [comment]
Will be fixed in next release.  Thanks

**Comment by jgonyea** [comment]
Fixed in latest release
