### ISSUE TITLE
Code simplification for datestamp fallback

### ISSUE THREAD

**Issue by aleclerc7** [jgonyea/grav-plugin-podcast#51]
Hello,

**partials/podcast_episodes_list.html.twig lines 12-18**:
```
            {% if (e.header.publish_date) %}
                {% set datestamp = e.header.publish_date %}
            {% elseif (e.header.date) %}
                {% set datestamp = e.header.date %}
            {% else %}
                {% set datestamp = e.modified %}
            {% endif %}
```
It can be written in one line:
`{% set datestamp = e.header.publish_date ?: e.header.date ?: e.modified %}`

Kind regards.

**Comment by jgonyea** [comment]
Thanks.  I'm aware of the ternary syntax, but I find the extra cognitive load to not be worth the lesser number of code lines.
