### ISSUE TITLE
Feed: Podcast title should come from page.header.podcast.title

### ISSUE THREAD

**Issue by aleclerc7** [jgonyea/grav-plugin-podcast#61]
Hello,

Ideally, `page.header.podcast.title` should be used in `feed.rss.twig` as the `<title>` value (line 11). The page's title can be used for other purposes, but the podcast title is what it is. But this would be a breaking change for actual users to make such a change. I nevertheless send this comment in case such a change would be considered in a future major version that would introduce breaking changes compared to previous versions.

Kind regards.

**Comment by karlquint** [comment]
+1, and the current description of the fields is misleading, says that RSS feed podcast title is from "Channel Meta" tab

**Comment by jgonyea** [comment]
Should be fixed now in v3.1.0
