### ISSUE TITLE
RSS feed validation by Apple with errors

### ISSUE THREAD

**Issue by karlquint** [jgonyea/grav-plugin-podcast#63]
When validating the RSS feed with Apple Podcast Connect, there is an error message complaining about image size. While it works for google podcasts and Spotify, the Apple issue persists. I triple-checked that all images are within the specs. 

I then tried to validate the generated RSS feed here: 

- https://podba.se/validate/?url=https://growdeeper.co/growdeeperpodcast.rss
- https://www.castfeedvalidator.com/?url=https%3A%2F%2Fgrowdeeper.co%2Fgrowdeeperpodcast.rss

Podbase complains that artwork download results in error: "Darn, I wasn’t able to retrieve the image (got a “” error)."

When validating the XML file here https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fgrowdeeper.co%2Fgrowdeeperpodcast.rss getting some errors. I realised e.g. that the image URLs have a double backslash (https://growdeeper.co**//**user/pages/...).

Maybe also one of the many other errors are the reason. Would appreciate if the developer could look into this.

**Comment by jgonyea** [comment]
Should be fixed in newest release, 3.1.0
